# Generated by Django 3.2.15 on 2022-09-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='category',
            field=models.CharField(choices=[('Electronics', 'electronics'), ('Books', 'books'), ('Crafts', 'crafts'), ('Sports', 'sports')], default='Electronics', max_length=20),
        ),
    ]
