# Generated by Django 3.2.15 on 2022-09-20 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_product_details_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
