# Generated by Django 3.2.15 on 2022-09-20 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_product_details_watchers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_details',
            name='watchers',
        ),
        migrations.AddField(
            model_name='product_details',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
