# Generated by Django 3.2.15 on 2022-09-23 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_product_details_geeks_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owneruser', to=settings.AUTH_USER_MODEL),
        ),
    ]
