# Generated by Django 3.2.15 on 2022-09-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_rename_bid_bid_bid_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comment_product',
        ),
    ]
