# Generated by Django 3.2.15 on 2022-09-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20220924_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
